services:
  web:
    build: .
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_URL=http://localhost:8000/api
    depends_on:
      - api
    stdin_open: true
    tty: true
  api:
    build: ./api
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - CORS_ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    volumes:
      - ./api:/var/www/html